# Generated by Django 4.1.6 on 2023-02-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Блокчейн', max_length=10, verbose_name='Блокчейн')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(help_text='Адрес кошелька', max_length=50, verbose_name='Адресс')),
                ('blockchains', models.ManyToManyField(to='wallets.blockchain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кошелька')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.CharField(max_length=20, verbose_name='Номер блока')),
                ('hash', models.CharField(max_length=50, verbose_name='Хэш транзикции')),
                ('tx_from', models.CharField(max_length=50, verbose_name='Отправитель')),
                ('tx_to', models.CharField(max_length=50, verbose_name='Получатель')),
                ('token_name', models.CharField(max_length=100, verbose_name='Название токена')),
                ('token_symbol', models.CharField(max_length=100, verbose_name='Символ токена')),
                ('value', models.CharField(max_length=20, verbose_name='Количество токенов')),
                ('time_stamp', models.DateTimeField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.blockchain')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
        ),
    ]
