# Generated by Django 4.1.6 on 2023-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название токена'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='blockchains',
            field=models.ManyToManyField(related_name='blockchain', to='wallets.blockchain'),
        ),
    ]
