# Generated by Django 4.1.6 on 2023-03-07 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_alter_transaction_token_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='name',
            field=models.CharField(default='blob', max_length=50, verbose_name='Full blockchain name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Blockchain'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block_number',
            field=models.CharField(max_length=20, verbose_name='Block number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=50, verbose_name='Tx hash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_symbol',
            field=models.CharField(max_length=100, verbose_name='Token symbol'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_from',
            field=models.CharField(max_length=50, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_to',
            field=models.CharField(max_length=50, verbose_name='Reciever'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to=settings.AUTH_USER_MODEL, verbose_name='Wallet owner'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(max_length=50, verbose_name='Wallet'),
        ),
    ]
